name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt requirements-dev.txt
    - name: Testing code with pytest
      run: |
        pytest tests/ --doctest-modules \
            --junitxml=junit/test-results.xml --cov=mysql_csv_import \
            --cov-report=xml --cov-report=html --cov-report=term
